---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
  labels:
    name: nginx-demo
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: nginx-demo-stack
